version: "3.7"

services:
  wordpress:
    image: wordpress
    env_file:
      - docker.env
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/wp-content/plugins/hugedevs-marketing-integration
